### ISSUE TITLE
When creating a new application, automatically select it in OpenShift Application Explorer

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#362] opened 2018-11-20 10:21 UTC
it avoids user to have to expand the project and then select the application

**Comment by dgolovin** [comment] 2018-11-21 10:37
Should be possible with this API https://code.visualstudio.com/docs/extensionAPI/vscode-api#TreeView%3CT%3E

**Comment by dgolovin** [comment] 2019-02-25 06:37
Closed as duplicate of generic one #630.

**Closed by dgolovin** 2019-02-25 06:37 UTC
Labels: kind/enhancement, resolution/duplicate
