### ISSUE TITLE
API token for sandbox login showing failed

### ISSUE THREAD

**Issue by Vatsal-Kathiriya** [redhat-developer/vscode-openshift-tools#4080] opened 2024-04-26 17:28 UTC
Type: <b>Bug</b>

## Steps to Reproduce

1.
2.
3. 

## Environment

Extension version: 1.13.0
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.70GB free)|
|Process Argv|--crash-reporter-id 8cbc38cd-84df-4743-a5f4-465b3fcceb3b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
showvideot:31016892
chatpanelc:31018788
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31022790

```

</details>

**Comment by mohitsuman** [comment] 2024-04-26 18:24
@Vatsal-Kathiriya can you add more details to the issue ?

**Comment by Vatsal-Kathiriya** [comment] 2024-04-26 19:09
Okay sir , when I click on get token button it looks me on website and from
there I copy API token and after coming back to vs code when I click on
login devtools it fails again and again

**Comment by vrubezhny** [comment] 2024-05-11 14:01
@Vatsal-Kathiriya Do you see any error messages? 
Or do you see a picture like the following after you added the cluster and provided its token to login?

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/bba5e39d-7f3e-4666-8aea-65bc2562062f)

**Comment by vrubezhny** [comment] 2024-05-30 22:57
@Vatsal-Kathiriya If the issue is still relevant...

Make sure you first opened OpenShift view on the Side Bar:
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/8064c7cc-d312-4e42-b3ff-8be9f6dc318b)

Then you may proceed with setting up a DevSandbox  from  `Welcome - OpenShift Toolkit` view:
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/9bbc14d8-bfed-419a-bca6-afe93c0458c3)

And try Launching Developer Sandbox :
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/b0f1c230-5f48-4727-8f11-d20b4cb7da79)
 
Feel free to register, and once done you'll see "our sandbox account has been provisioned and is ready to use." message:
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/b0df1f30-e325-40bd-b5ab-520f122173af)

So, now you need to click "Get Token" button - a web page with a link "Display token" will be opened in your browser, so...
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/24751e39-2b62-44d4-8667-ddc25cd1f3e4)

 click on it and on the following page copy the token (!Make sure you're not copying any extra characters or whitespaces):
 ![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/00976f35-2c95-4673-bd05-38d8b2af698c)
 
Now the "Login to DevSandbox" button should become "enabled":
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/911d8447-f644-490d-98d8-6b7fa35e0a16)

... so you can click it and finish logging in to your DevSandbox cluster, so the App. Explorer tree should show the connected cluster:
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/03da1ec1-d6e8-4336-870d-253aeaae4918)

**Comment by vrubezhny** [comment] 2024-05-30 23:39
If this doesn't work...

You can manually add the Dev Sandbox cluster and log in to it using the same token...

Press "Login" button:
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/1ab99624-62d5-455a-851a-cd2a5f3114b0)

In the quick pick appeared select "Provide new URL...":
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/fb16fa6b-fccc-44ac-88c8-7e56f01bd00d)

... and type in (or copy/paste) the URL of the DevSandbox cluster and press "Enter" (you could find it on the same Web page where you were copying your token from.  For me it shows: "https://api.sandbox-m3.1530.p1.openshiftapps.com:6443":
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/54483909-7189-4b03-83eb-d5de0e4a2052)

... then select "Login using Token":
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/861132a2-bc79-4089-a198-76452885ecc4)

... next paste your API token to the input field and press Enter (you can copy your token from the same Web page opened previously by "Get Token" button on the `Welcome - OpenShift Toolkit` view):
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/eca6ceb3-cb23-4945-8ded-6a69dddae1f6)

Now you should be logged in to the DevSandbox cluster:
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/a448825c-9aa8-4778-8c86-77bfbc2bdf1c)

**Comment by Vatsal-Kathiriya** [comment] 2024-05-31 03:55
Thanks, I'll check it out.

**Comment by mohitsuman** [comment] 2024-07-25 18:42
@Vatsal-Kathiriya did the fix help you to get the workflow running ? Please update and accordingly we can fix or close the issue.

**Closed** 2024-08-07 06:55 UTC
