### ISSUE TITLE
execute in terminal creates a new terminal named 'OpenShift' with every call

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#457] opened 2018-12-05 15:31 UTC
Every time a command is executed in terminal, it creates a new terminal with the same name: OpenShift. This makes it quite hard to identify which one is which, especially if you end up with lots of them.

**Comment by dgolovin** [comment] 2018-12-05 17:20
Duplicate of **#217 Too many OpenShift terminals**.

**Closed by dgolovin** 2018-12-05 17:20 UTC
Labels: kind/bug, resolution/duplicate
