### ISSUE TITLE
Port selection on new URL is skipped when a URL already exists

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1573] opened 2020-05-18 08:20 UTC
Happens when multiple ports are available for a component (like a java app having 3 available ports). Creating the first URL will prevent the user from choosing ports for any other URL they wish to create afterwards.

**Comment by mohitsuman** [comment] 2020-05-18 08:57
@jrichter1 For test, can you link the java component you tried. I will use the same to debug and fix.

**Comment by jrichter1** [comment] 2020-05-18 09:04
https://github.com/oskutka/rhlp :)

**Comment by mohitsuman** [comment] 2020-05-18 12:43
So the issue is pertaining to odo.

- If we create a new url for first time, the `odo describe` output shows this:

<img width="769" alt="Screenshot 2020-05-18 at 6 07 45 PM" src="https://user-images.githubusercontent.com/3133356/82214156-0127f880-9933-11ea-9d84-92a69b646633.png">

- Now when we start to create a new URL, the `odo describe` output just shows one port entry which has been selected previously.

<img width="799" alt="Screenshot 2020-05-18 at 6 12 38 PM" src="https://user-images.githubusercontent.com/3133356/82214273-303e6a00-9933-11ea-8734-9454f8a05e5e.png">

Will raise an upstream issue for the same.

**Comment by mohitsuman** [comment] 2020-05-18 12:52
Upstream : https://github.com/openshift/odo/issues/3201

**Comment by mohitsuman** [comment] 2020-06-05 13:29
This is fixed in odo 1.2.2. Will test this out once we migrate to odo 1.2.2

**Comment by dgolovin** [comment] 2020-07-06 22:24
Resolved with migration to odo 1.2.2.

**Closed by dgolovin** 2020-07-06 22:24 UTC
Labels: kind/bug, upstream/odo
