### ISSUE TITLE
Login to cluster does not work

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2693] opened 2022-12-02 16:57 UTC
On MacOS when trying to login to a cluster I get this message
Failed to login to cluster 'https://api.ocp2.adapters-crs.ccitredhat.com:6443' with 'Command failed: "/Users/lgrossma/.vscode/extensions/redhat.vscode-openshift-connector-1.0.1/out/tools/darwin/odo-darwin-amd64" login https://api.ocp2.adapters-crs.ccitredhat.com:6443 -u='developer' -p='developer' --insecure-skip-tls-verify ✗ x509: “kube-apiserver-lb-signer” certificate is not trusted '!

This is probably cause by same issue as here: https://bugzilla.redhat.com/show_bug.cgi?id=2097830 and thus MacOS specific issues. However, when testing for the 1.0.0 release, login worked without problems. Maybe it is also caused by MacOS 13

**Comment by dgolovin** [comment] 2022-12-03 03:10
@lgrossma could you try if 
```/Users/lgrossma/.vscode/extensions/redhat.vscode-openshift-connector-1.0.1/out/tools/darwin/oc" login https://api.ocp2.adapters-crs.ccitredhat.com:6443/ -u='developer' -p='developer' --insecure-skip-tls-verify``` 
works as expected for you?

**Comment by dgolovin** [comment] 2022-12-03 03:15
@lgrossma The only thing changed is odo binary. Could you also download latest release from [here ](https://developers.redhat.com/content-gateway/rest/mirror2/pub/openshift-v4/clients/odo/v3.3.0/odo-linux-amd64.tar.gz )and see if that works?

**Comment by lgrossma** [comment] 2022-12-05 11:26
So the version for MacOS does not work. Seems like it is the same issue as it is with the oc..

**Comment by mohitsuman** [comment] 2022-12-05 11:34
We are moving to odo 3.3.0 for the next iteration. This is the macOS binary for it https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/odo/v3.3.0/odo-darwin-amd64.tar.gz

Can you check if this macOS binary works for you ? So that we understand if the issue is with binary or something else.

**Comment by lgrossma** [comment] 2022-12-05 12:07
Still having the same error. Look at this: https://bugzilla.redhat.com/show_bug.cgi?id=2097830 seems that the problem that is happening in the OC is caused by golang and have not beed fixed yet. Not sure how odo is implemented, but I guess the cause will be probably the same..

**Comment by lgrossma** [comment] 2022-12-06 10:14
> Yes, `odo` is in the same situation as `oc`. I'm afraid that there is not much we can do :-/
> 
> What I do on my system is I export OpenShift certificate and mark it as trusted on my system. This is described in one of the comments at https://bugzilla.redhat.com/show_bug.cgi?id=2097830#c27

That is true. However, that workaround only works for login with token if I am not mistaken so the issue for other login method still remains.

**Comment by mohitsuman** [comment] 2022-12-06 11:01
If this is macOS 13 issue, we can just mark it as known issue and pin it. Hopefully by next release, the oc and odo issue will get resolved.

**Comment by lgrossma** [comment] 2022-12-06 11:03
> If this is macOS 13 issue, we can just mark it as known issue and pin it. Hopefully by next release, the oc and odo issue will get resolved.

I'm afraid that this is macOS general issue

**Comment by mohitsuman** [comment] 2022-12-06 11:06
@lgrossma So let's say we use the 1.0 release and use odo 3.0 there, then it works on macOS perfectly? But when we move to 3.3.0, then the login fails on macOS (any version). If yes, then this is a blocker for the release.

**Comment by lgrossma** [comment] 2022-12-06 11:10
@mohitsuman exactly as you say

**Comment by dgolovin** [comment] 2022-12-07 06:15
@lgrossma @mohitsuman @kadel on vscode side we can use oc to login, we keep oc 4.9 and this should let us to do release. WDYT?

**Comment by dgolovin** [comment] 2022-12-07 07:29
I am going to push it master, to get new nightly build available for testing.

**Closed** 2022-12-07 07:54 UTC
Labels: priority/blocker, priority/critical, kind/bug

**Comment by odockal** [comment] 2022-12-07 15:24
@dgolovin @lgrossma @mohitsuman Guys, I do not have a mac to verify this. If someone could do that, please.
