### ISSUE TITLE
Can't start dev on podman

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#3930] opened 2024-02-23 14:13 UTC
"Start Dev on Podman" opens terminal with following error
```
unable to access podman. Do you have podman client installed and configured correctly? cause: timeout (1s) while waiting for Podman version
```

This happens on MacOS 14.3 and running `/Users/lgrossma/.odo/cache/3.15.0/odo-darwin-amd64 dev --platform podman --forward-localhost` directly from terminal works just fine.

**Comment by datho7561** [comment] 2024-02-26 20:50
I can't reproduce this issue, I tried on my Linux machine and my Windows machine (I don't have a Mac). My best guess as to what's happening is that we aren't passing the environment from the shell to `odo dev` properly.

**Comment by datho7561** [comment] 2024-02-27 16:28
I tried the following to replicate the issue:
- Create a Fedora VM that doesn't have `podman` installed
- Build the podman binary from source
- Place the podman binary in `~/bin/`, and put `~/bin/` on the PATH
- Run vscode with , then run "Start Dev on podman" on a component

However, I wasn't able to replicate the issue. This means my guess as to what the problem is is incorrect.

**Comment by msivasubramaniaan** [comment] 2024-02-28 14:14
I tried with MacOS `Sonoma 14.0` and I couldn't replicate this issue.

**Comment by lgrossma** [comment] 2024-02-29 09:48
I still have this issue even after release

https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/cff95f0e-a1d5-43da-91bf-8016bff6c527

**Comment by lgrossma** [comment] 2024-02-29 14:22
@datho7561 No, I am still running on intel..

**Comment by datho7561** [comment] 2024-02-29 14:55
hmmm.

**Comment by mohitsuman** [comment] 2024-04-02 16:02
@lgrossma @datho7561 what is the update on this issue ? Is this still on mac Intel based?

**Comment by lgrossma** [comment] 2024-04-07 14:36
I am still having this issue

**Comment by mohitsuman** [comment] 2024-04-10 14:17
As discussed, it works on mac based system, hence closing this.

**Closed by mohitsuman** 2024-04-10 14:17 UTC
Labels: kind/bug
