### ISSUE TITLE
OpenShift shows successful login via credentials, does nothing

### ISSUE THREAD

**Issue by pugantsov** [redhat-developer/vscode-openshift-tools#2794] opened 2023-03-17 11:56 UTC
I am currently attempting to connect to my OpenShift cluster via credentials (also via a VPN to access the URI). I am able to SSH and Remote Connect to my allocated volume but not via the OpenShift Toolkit. 

When I log in with credentials, I get a notification in the right-hand corner that says "Successfully logged in to {URI}" yet the Application Explorer still shows "Cluster is not accessible or you are not logged in." and when I press login, the URI is not saved and nothing has changed.

Are there any logs I can inspect to see what is going on?

To add to this, a colleague of mine is able to log in without any issues or additional setup.

Kubernetes Version: v1.3.11
OpenShift Toolkit Version: v1.2.0

**Comment by mohitsuman** [comment] 2023-03-17 12:06
Hi @pugantsov thanks for raising this up. Can you help us with what type of OpenShift Cluster you are connected to ?

You can see the full log from the Terminal View of VSCode. 
- Once you open the `Terminal` , there is a drop down on right side and you have to Select `OpenShift`. 
- Once that is selected, you can scroll up to see all the login actions performed and projects present in the cluster after successful login.

<img width="1229" alt="Screenshot 2023-03-17 at 5 33 24 PM" src="https://user-images.githubusercontent.com/3133356/225899689-b1d0e894-4ec3-40ec-9e11-4d241c045d3a.png">

**Comment by mohitsuman** [comment] 2023-03-22 12:30
It depends on the cluster where it is hosted and from which region it is called from ? What OpenShift are you using ?

**Comment by mohitsuman** [comment] 2023-05-25 20:05
Hey @pugantsov it looks like the problem is solved at your end. I am closing the issue, please feel free to open a new issue if you encounter any issue with extension usage or want any specific feature to be added.

**Closed by mohitsuman** 2023-05-25 20:05 UTC
