### ISSUE TITLE
Create Quick start document describing how to deploy wildwest application with extension

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1531] opened 2020-05-02 00:51 UTC
Documenting how to deploy wildwest app would be a good candidate for Quick start document. 
App consists of [frontend ](https://github.com/openshift-evangelists/Wild-West-Frontend) and [backend](https://github.com/openshift-evangelists/Wild-West-Backend) and require additional oc commands executed.
Final working app looks like this

![image](https://user-images.githubusercontent.com/620330/80851018-e97f0f00-8bd3-11ea-8c9c-9ee336300a88.png)

**Comment by datho7561** [comment] 2023-07-17 15:26
Last Friday, I worked through this demo using vscode-openshift. Here are the pain points I encountered while getting it to work with the extension:

### 1.
In order to make the backend accessible to the front end, you must run `oc expose svc wildwest-backend-app`. There is no nice way to do this from within VS Code using a UI. I tried using the port forwarding provided by `odo` to access the backend from the frontend, but it doesn't work.

On vanilla Kubernetes, you can't use `oc expose svc wildwest-backend-app`, since Routes are an extension on to Kubernetes provided by OpenShift. Instead, you must create the following YAML file then run `kubectl apply -f file.yaml`. You also need to ensure you have an ingress controller set up (by default on `minikube` I have the nginx ingress controller).

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildwest-backend-ingress
spec:
  defaultBackend:
    service:
      name: wildwest-backend-app
      port:
        number: 8080
```

### 2.
In order to point the front end to the back end, you must pass environment variables containing the URL and port of the back end to the front end. You can do this through modifying the `devfile.yaml` of the front end service:

```diff
diff --git a/devfile.yaml b/devfile.yaml
index 4f86869..1b90b6e 100644
--- a/devfile.yaml
+++ b/devfile.yaml
@@ -37,9 +37,18 @@ components:
     memoryLimit: 1024Mi
     mountSources: true
     sourceMapping: /project
+    endpoints:
+    - name: nodejs
+      targetPort: 8080
+      exposure: internal
+    env:
+      - name: COMPONENT_BACKEND_HOST
+        value: 192.168.39.178
+      - name: COMPONENT_BACKEND_PORT
+        value: '80'
   name: runtime
 metadata:
-  name: nodejs
+  name: wildwest-frontend
   version: 2.0.0
 schemaVersion: 2.0.0
 starterProjects:
```

This is not good, since this value will get committed to the repo, and the URL/IP that the backend gets assigned depends on the cluster and might change whenever the Route/Ingress is deleted and recreated.

### 3.
I haven't been able to get the game to work properly on vanilla Kubernetes. This is because, as a part of the game, the backend tries to access a bunch of Kubernetes objects, some of which are OpenShift specific, like Routes. This is probably fine, since the application was designed for OpenShift and we can demo the app using OpenShift.

### 4.
The frontend's `package.json` needs to be modified in order for dev mode to work. This is because the devfile supports running the application in debug mode by running `npm run debug`, but the package.json doesn't have a script called `debug`. vscode-openshift doesn't have a context menu to run the application in non-debug mode. I manually created the `debug` script, which just runs the `run` script:

```diff
diff --git a/package.json b/package.json
index c90dc29..753e206 100644
--- a/package.json
+++ b/package.json
@@ -5,7 +5,8 @@
   "main": "server.js",
   "scripts": {
     "start": "node server.js",
-    "test": "echo \"Error: no test specified\" && exit 1"
+    "test": "echo \"Error: no test specified\" && exit 1",
+    "debug": "npm run start"
   },
   "repository": {
     "type": "git",
```

**Comment by datho7561** [comment] 2023-08-15 15:22
I realized I misunderstood how the wild west application works. We can get it working using less steps. I updated the previous message accordingly.

**Comment by datho7561** [comment] 2023-08-15 15:51
I just read https://odo.dev/blog/binding-database-service-without-sbo, and it seems you can just use the name of the service as the hostname, instead of having to read the name of the service from the web UI. This simplifies two things:
- you don't need to use the CLI or OpenShift/Kubernetes web dashboard to figure out what the host is
- you can safely commit the environment variable configuration to the repo, seeing as the hostname and port won't change between systems or clusters

**Closed** 2023-08-31 20:44 UTC
Labels: kind/task, component/documentation, demo
