### ISSUE TITLE
Cancelling Select Component Type window not working normally

### ISSUE THREAD

**Issue by TrevorBenson** [redhat-developer/vscode-openshift-tools#2929] opened 2023-06-01 16:21 UTC
Type: <b>Bug</b>

## Describe the bug

After clicking on the **Create Component** button in the **COMPONENTS** side panel the Select Component type window opens. Nothing seems to close this window except selecting an item, or key sequence to change window and cancelling that one.

* Hitting escape doesn't close the window or cancel the selection process.
* Clicking on the main IDE interface outside the selection window does not close it.
* Pressing **ctrl-shift-p** changes the window. After this hitting escape and other methods to back out of a popup selection window work

## Expected Behavior
Hitting escape or clicking outside the selection window would cancel the action, uncovering the editor windows and returning to basic IDE editor interface.

## Current Behavior
Window is stuck on top of editor window. Depending on the screen resolution and layouts some or most of the text in the editor may not be visible until the window is closed.

## Steps to Reproduce
1. Click the OpenShift extension to open its side panel.
2. Be connected to a Openshift cluster (I was using sandbox)
3. Click the **Create Component** button.
4. Observe the **Select Component type** window remain open when pressing esc, or clicking anywhere in the IDE that would normally deselect the popup window.

## Environment
* Linux OS
  * kernel 6.2.9-200.fc37 
* Code version 1.78.2-1683731087.el7

Extension version: 1.4.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 6.2.9-200.fc37.x86_64
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 3940)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|30.98GB (10.84GB free)|
|Process Argv|--unity-launch --crash-reporter-id 580bece0-b191-4d8a-b8bf-253607cede2d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by datho7561** [comment] 2023-06-02 15:36
> Hitting escape doesn't close the window or cancel the selection process.

I can't seem to replicate this part unfortunately. Hitting Escape works for me. I'm on RHEL 8, so maybe it's something platform specific. I'll try it out with Fedora next Monday.

We are planning on replacing this interface soon (see https://github.com/redhat-developer/vscode-openshift-tools/pull/2844 and https://github.com/redhat-developer/vscode-openshift-tools/issues/2922), but it still would be nice to fix it for the time being.

**Comment by datho7561** [comment] 2023-06-02 19:15
> I clicked Import from Git. The import started, but then the progress bar hung for a few minutes at some %

I ran into many bugs while trying to reproduce this bug, I don't think any were the one you mentioned:

### Bug 1

1. Use SSH keys for authenticating with GitHub instead of username/password (this might be enforced by GitHub nowadays, I'm not sure though)
2. I create a private repo on GitHub
3. I enter the URL of the repo in the import dialog, despite the fact that you normally use `git@github.com/...` to clone repos when you use keys to authenticate with GitHub.
4. The "enter username for github.com" popup appears
5. Close it without entering anything
6. The UI is stuck at the importing from URL step. No progress is indicated.

### Bug 2

Regardless of what repo you use, if doesn't contain a `devfile.yaml`, then the form fails with the error message "Issue on Parsing Git URL/devfile". We don't communicate anywhere that a `devfile.yaml` is needed, and there's no reason we should require one, since we can let the user pick the tech stack in the UI and generate the devfile from that.

### Bug 3

If the "Import from Git" fails, the repo remains cloned on your computer, although this is not communicated well.

> However now both windows close when using escape key and other methods.

Which two windows? As in you can close the 'Select context folder' and 'Select Component Type' using Escape?

**Comment by TrevorBenson** [comment] 2023-06-02 23:08
> Use SSH keys for authenticating with GitHub instead of username/password (this might be enforced by GitHub nowadays, I'm not sure though)

This is definitely enforced at the org level for each private repo in the Workspace I was using. The import "appeared" to start a clone operation from what I recall, although I think it was inside a terminal at the bottom.

> Which two windows? As in you can close the 'Select context folder' and 'Select Component Type' using Escape?

Correct, both the 'Select context folder' and 'Select Component type' allowed me to cancel the operation on my second pass (not requiring **ctrl-shift-p** or any other tricks to change the dropdown first).

I'll uninstall and reinstall extensions and see if I can reproduce it. If not maybe the issue should be closed? Eliciting 3 new and reproducible bugs along the way is probably more beneficial than the issue itself :grin:

**Comment by datho7561** [comment] 2023-06-05 15:24
> although I think it was inside a terminal at the bottom.

Interesting, i didn't notice this part when trying it. I'll have to take a better look into how the clone is performed.

> maybe the issue should be closed?

Okay. If you can't reproduce the issue, I think this is a good idea. I can make separate issues for the issues I ran into.

> Eliciting 3 new and reproducible bugs along the way...

Yes, thank you so much for filling this issue! Hopefully we can better communicate what is expected of the user in the reworked "create component" UI.

**Closed** 2023-06-05 16:09 UTC
