### ISSUE TITLE
Provide command to migrate components created with v0.0.23 or earlier

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1551] opened 2020-05-09 07:05 UTC
This will stop auto migration/import of resources. Sometimes there can be multiple namespaces in the cluster and auto migration scans through all of them and thus delays the tree loading.

We can have an Update provided to the user to perform the update as per need and import the resources.

**Comment by dgolovin** [comment] 2020-05-11 06:25
Duplicate of #1430.

**Closed by dgolovin** 2020-05-11 06:25 UTC
Labels: demo, kind/enhancement, resolution/duplicate
