### ISSUE TITLE
Add OpenShift binaries to Dev Containers

### ISSUE THREAD

**Issue by adambkaplan** [redhat-developer/vscode-openshift-tools#2840] opened 2023-04-19 16:20 UTC
[Dev Containers](https://code.visualstudio.com/docs/devcontainers/containers) is a potentially powerful extension to VSCode. One of the neat features is that it lets you declaratively install extensions into a dev container.

The VSCode extension for Kubernetes seems to install `kubectl` onto the container, under `/root/.local/state`. The OpenShift extension doesn't seem to do this automatically for `oc` and other tools.

**Comment by datho7561** [comment] 2023-05-26 14:15
Related is https://github.com/redhat-developer/vscode-openshift-tools/issues/2872. In fact, it seems that issue is a duplicate of this one

**Closed** 2023-06-06 17:25 UTC
Labels: kind/enhancement

**Comment by mohitsuman** [comment] 2023-06-07 21:17
@adambkaplan We have implemented this feature in the latest 1.5.0 release. Can you please try and let us know if it works as expected for you. Thanks.
